name: Documentation
on:
  push:
    branches: [ main, feature/*, refs/pull/*/merge ]
  pull_request:
    types: [ opened ]
    branches: [ "main" ]
    paths:
      - "docs/**"
jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    container:
      image: andreiolar1/python-poetry-mkdocs:latest
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      - name: sanity Check
        run: (pwd && ls -la)
      - name: Run mkdocs
        run: mkdocs build -c
      - name: Publish Github Pages
        run: mkdocs gh-deploy
